New sleuth api for wavefront
wavefrontHQ/wavefront-spring-boot pull request #105
Opened 2021-02-19 12:38 UTC by marcingrzejszczak

with this change any Sleuth compliant tracer (Brave, OTel) can work with Wavefront out of the box (e.g.https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/pull/16)

2021-02-19 19:48 UTC, jonatan-ivanov approved these changes

2021-02-24 07:23 UTC, hanwavefront requested changes
A couple very minor nits, LGTM otherwise.  Thanks!

2021-02-24 07:23 UTC, hanwavefront commented on wavefront-spring-boot/src/main/java/com/wavefront/spring/autoconfigure/WavefrontTracingSleuthConfiguration.java
> +
nit: extra line breaks

2021-02-24 07:23 UTC, hanwavefront commented on wavefront-spring-boot/src/test/java/com/wavefront/spring/autoconfigure/WavefrontAutoConfigurationTests.java
> +            Set<String> traceDerivedCustomTagKeys = (Set<String>) ReflectionTestUtils.getField(
nit: indentation

2021-02-24 07:38 UTC, marcingrzejszczak commented
Applied the changes

2021-02-24 07:39 UTC, hanwavefront approved these changes

2021-02-24 07:45 UTC, merged