Aligning with autoconfiguration changes in Sleuth
wavefrontHQ/wavefront-spring-boot pull request #92
Opened 2020-11-23 10:22 UTC by marcingrzejszczak

To be merged once this https://github.com/spring-cloud/spring-cloud-sleuth/tree/autoconfig_refactoring_3 is merged

2020-11-23 13:15 UTC, snicoll requested changes
Thanks for the PR @marcingrzejszczak. Can you please revert your changes to the READMe and force push an update?

2020-11-23 13:15 UTC, snicoll commented on README.md
> +* Spring Boot 2.4 or above
Please revert this. We have a version of this starter that works with 2.3

2020-11-23 13:15 UTC, snicoll commented on README.md
> +        <version>2.1.0</version>
Updating the auto-configuration to work with the latest snapshot of Spring Cloud is unrelated to this. Besides `2.1.0` does not exist yet so that would lead to invalid instruction.

2020-11-23 13:15 UTC, snicoll commented on README.md
> +      mavenBom "com.wavefront:wavefront-spring-boot-bom:2.1.0"
Updating the auto-configuration to work with the latest snapshot of Spring Cloud is unrelated to this. Besides `2.1.0` does not exist yet so that would lead to invalid instruction.

2020-11-23 13:15 UTC, snicoll commented
Let's wait for a Spring Cloud milestone that adds support for this.

2020-11-23 15:59 UTC, marcingrzejszczak commented
Done

2020-11-25 12:39 UTC, snicoll approved these changes
Thank you for the follow-up Marcin.

2020-12-04 12:54 UTC, snicoll commented
I used a wrong GitHub issue ID in the commit message, sorry about that. This is fixed by dd1831e97a770ea36820c2c. Thanks @marcingrzejszczak!

2020-12-04 12:54 UTC, closed without merging